### PR TITLE
[#8] Chat Screen UI Implementation

### PR DESCRIPTION
**Pull request by MaxHvesser**
## Description

_I have added layout files including; `activity_chat`, `row_message_partner` and `row_message_sender`. These files are in preparation for the functionality that will inevitably come._

_I have also added the various value resources needed to make this happen. I followed the Adobe XD designs as closely as possible (changing some small values as needed along the way)._

_See the preview below of how this looks on a device._

## Type of Changes?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Testing Suites

## Checklist:
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [    ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings

| Preview of changes |
| -------------------- |
| Screenshot_20191013-202732_ChatAir-android |

### CODE REVIEW

**Comment by MaxHvesser** [comment]
@iadeelzafar I hadn't actually removed these, it was an inadvertent conflict from the recently merged [#17 ](https://github.com/ChatAir/ChatAir-android/commit/ef0d30393ae8d609a1ac4b08a95125010596ef7e) on master causing an issue due to me forking the project at an earlier commit.

If I had not forked from an earlier commit this wouldn't be an issue. I can however merge master into my branch.

**Comment by MaxHvesser** [comment]
This branch has now been merged with master.

**Comment by iadeelzafar** [comment]
@MaxHvesser I thought the same at first that it would've been because you forked before #17 got merged but I was confused looking at **File Changes** showing those files as removed in this commit.

**Comment by AminullahTajMuhammad** [comment]
@iadeelzafar merge this

**Comment by iadeelzafar** [comment]
🙌 Thank you for your contribution @MaxHvesser . We're looking forward to your contributions in the future to **ChatAir**. Cheers!

**Pull request merged**
