### PR TITLE
Implement ForgotPassword Screen

### PR DESCRIPTION
**Pull request by pfieffer**
## Description
- Description of issue: Implement ForgotPassword Screen
- Output before solved: No ForgotPassword Screen
- Changes in Issue: Add ForgotPasswordActivity and corresponding XML, Implement MaterailComponent Base Theme, make style for Button, Text, add Dimensions
- Output of solved issue: Can open ForgotPassword Screen after setting it as Launcher Activity

## Type of Changes?
Just put an x in the [ ] which are valid.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Testing Suites

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes.
- [x] ./gradlew assembleDebug assembleRelease

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by pfieffer** [comment]
Screenshots:
device-2019-10-23-105406
device-2019-10-23-105337
device-2019-10-23-105351

**Comment by pfieffer** [comment]
Any updates on this?

**Comment by AminullahTajMuhammad** [comment]
@iadeelzafar merge this PR.

**Comment by pfieffer** [comment]
Thank you. :) and hope I will be contributing more.

**Pull request merged**
